name: restfull_api
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0-287.0.dev # Ganti ke versi stabil (misal: '>=3.0.0 <4.0.0')

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ==================================
  # DITAMBAHKAN UNTUK JSON SERIALIZATION
  # ==================================
  json_annotation: ^4.8.1

  # ==================================
  # DITAMBAHKAN UNTUK KONEKSI API DAN PENYIMPANAN LOKAL
  # ==================================
  http: ^1.1.0 # Diperlukan untuk RESTful API
  shared_preferences: ^2.2.2 # Diperlukan untuk menyimpan data lokal
  intl: ^0.18.1 # Versi terbaru saat ini

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ==================================
  # DITAMBAHKAN UNTUK JSON SERIALIZATION
  # ==================================
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.